Poker:
	gcc -o Poker Poker.c

Poker_asm:
	gcc -S Poker.c -o Poker_asm.s

Poker_in:
	gcc -O2 -finline-limit=500 -o Poker_in Poker.c

Poker_in_asm: 
	gcc -O2 -finline-limit=500 -S Poker.c Poker_in_asm.s

Simple:
	gcc Simple.c -o Simple

Simple_O:
	gcc -O2 -o Simple_O Simple.c

Simple_asm:
	gcc -S Simple.c Simple_asm.s

Simple_asm_O: 
	gcc -O2 -S Simple.c Simple_asm_O.s

